### ISSUE TITLE
ZERO_RESULTS not an error

### ISSUE THREAD

**Issue by ewgRa** [googlemaps/google-maps-services-go#115]
For now, when geocoding request have response status ZERO_RESULTS, it is considered as error.

Looks really strange, since it is not an error. 
On such response status my service will response 204 for example.
When status 'OK' - then just response 200
In another cases it is really error and I want log it and response 500

I see only one way to achieve it  - 'if err != nil && err == "maps: ZERO_RESULTS - "' and it is really ugly.  

I have call "result, err := c.Geocode(context.Background(), r)". Any idea how to make it not so ugly?

For me more natural looks PR to Geocode func, that will check if response status "ZERO_RESULTS", than just return empty results. Is such PR have change to be merged, since it will broke backward compatibility?

**Comment by domesticmouse** [comment]
Please raise a PR, I'll merge it.

**Comment by ewgRa** [comment]
PR done #116

**Comment by domesticmouse** [comment]
Thanks!
