### ISSUE TITLE
Bad annotation for PlaceAutocompleteRequest struct

### ISSUE THREAD

**Issue by andydennisonbooth** [googlemaps/google-maps-services-go#124]
Thinking `Query Autocomplete` needs to be replaced with `Place Autocomplete` in this comment.

https://github.com/googlemaps/google-maps-services-go/blob/ba53c52a51b633aa2d8a247f126f86b299875c34/places.go#L710

**Comment by domesticmouse** [comment]
Thanks for finding that @andydennisonbooth =)
