### ISSUE TITLE
Can't install using govendor

### ISSUE THREAD

**Issue by facundomedica** [googlemaps/google-maps-services-go#127]
If I try to run:'m getting this
```
go get googlemaps.github.io/maps
can't load package: package googlemaps.github.io/maps: no Go files in /Users/myuserhere/Documents/Projects/Go/src/googlemaps.github.io/maps
```

I've tried to go get this repository, but there are internal imports that refers to googlemaps.github.io

**Comment by domesticmouse** [comment]
I've had a quick look at https://github.com/kardianos/govendor/blob/master/doc/dev-guide.md but I can't tell what I'm required to add to this package for `govendor` to correctly import this package.

**Comment by facundomedica** [comment]
@domesticmouse thanks for the swift response! I think that the problem is the redirect that you do (the `googlemaps.github.io/maps` thing).

**And I have to correct myself, `go get` command is what doesn't work.**

Also: Usually you don't have to do anything to the project to make it work with govendor.

**Comment by domesticmouse** [comment]
I'm glad it worked out! =)
