### ISSUE TITLE
Gecoding API isn't supported by Client SDK with placeid parameter in request

### ISSUE THREAD

**Issue by mojospirit** [googlemaps/google-maps-services-go#128]
Hi, when I used client sdk library to request Geocoding API with placeid parameter, I got following error  return 'google client cannot get geocoding response from server because **_maps: address, components and LatLng are all missing_'.**

**Comment by kkshetty** [comment]
Hey @mojospirit,

If you're trying to fetch the address for a given place_id, you can always the Reverse Geocoding API.

The method in this case would be the ReverseGeocode() method => https://github.com/googlemaps/google-maps-services-go/blob/master/geocoding.go#L61

This method requires either a LatLng or a PlaceID to set in the *GeocodingRequest object that you pass as the second argument.

**Comment by mojospirit** [comment]
@kkshetty , Thanks a lot. It seems because I use the Geocode API.

**Comment by domesticmouse** [comment]
I'd suggest the right API endpoint to call when you want the address for a Place ID is the [Place Details](https://developers.google.com/places/web-service/details) endpoint.
