### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by ebati** [googlemaps/google-maps-services-go#135]
Errors are not differentiated so handling different errors is not possible right now.

As an example, OVER_QUERY_LIMIT error is returned from google but can not be checked (this will not be an issue for single instance as rate limiting will prevent this case but can be an issue if multiple instances are running. ZERO_RESULTS is also handled and return empty response for geocoding but it is not handled for other requests (like reverse geocoding).

commonResponse might be made public with defined status list and returned errors can be checked for type match. Or errors can be differentiated like temprory etc. and implements Temprory function (like http package).

If agreed on a solution i can work on the issue.

**Comment by domesticmouse** [comment]
Please feel free to sketch out an initial implementation of how errors should be propagated. I'll happily take input on how to improve this library.

/cc @samthor who has a lot more knowledge of how Go code should be written than I.

**Comment by samthor** [comment]
There's two approaches I suppose. Either define different `Err...` objects that are returned, e.g. `ErrOverQueryLimit`, or add helper methods:

```go
  if maps.IsOverQueryError(returnedErr) {
    ..
  }
```

**Comment by peergynt** [comment]
@ebati have you made any progress on this issue?

I too would be interested in a more consistent error handling.
For instance, the Places API implementation still treats ZERO_RESULTS as an error.

I was personally thinking that ZERO_RESULTS should not return an error but an empty response (per the API docs: ZERO_RESULTS indicates that the search was successful but returned no results).
It would be nice to be able to differentiate between the other errors without having to compare the error string!

I could take a stab at it if it helps.

**Comment by ebati** [comment]
Since we moved to a different provider, i didnt use this library so i couldnt make time to work on this. I should have noted here. Sorry for that😓

**Comment by superstas** [comment]
@peergynt it would be great if you could send a PR with a consistent ZERO_RESULTS handling approach.
It'd help us a lot.

Thx!
