### ISSUE TITLE
Golang Directions SDK does not optimize waypoints

### ISSUE THREAD

**Issue by silverspace** [googlemaps/google-maps-services-go#138]
The Directions API does not optimize waypoints when the request specifies Optimize: true.

The issue is that the golang SDK adds `optimize=true` as its own query parameter, when it should be part of the `waypoints` query parameter as `optimize:true|...`. 

Example of *working* URL from https://developers.google.com/maps/documentation/directions/intro#Waypoints:
```
https://maps.googleapis.com/maps/api/directions/json?origin=Adelaide,SA&destination=Adelaide,SA&waypoints=optimize:true|Barossa+Valley,SA|Clare,SA|Connawarra,SA|McLaren+Vale,SA&key=YOUR_API_KEY
```

The issue here is that https://github.com/googlemaps/google-maps-services-go/blob/master/directions.go#L91 adds optimize as a separate query parameter, rather than appending the waypoint string `"optimize:true"`. 

The result is a *broken* URL:
```
https://maps.googleapis.com/maps/api/directions/json?optimize=true&origin=Adelaide,SA&destination=Adelaide,SA&waypoints=Barossa+Valley,SA|Clare,SA|Connawarra,SA|McLaren+Vale,SA&key=YOUR_API_KEY
```

**Comment by febytanzil** [comment]
found the same issue,
```routes, _, err := c.Directions(context.Background(), &maps.DirectionsRequest{
		Origin:      origin.String(),
		Destination: origin.String(),
		Waypoints:   wpArr,
		Optimize:    true,
	})
log.Println(routes[0].WaypointOrder)
```
was trying like this with different permutations of waypoints, but always return ordered integer 0, 1, etc. even optimize is set to true
