### ISSUE TITLE
I/O Timeout

### ISSUE THREAD

**Issue by felangga** [googlemaps/google-maps-services-go#139]
Hello, I'm running this on my localhost and failed to run the example code, here the error 

> INFO  12:20:59    app library.go:31: fatal error: Get https://maps.googleapis.com/maps/api/directions/json?destination=Perth&key=Axxxxxx &origin=Sydney: dial tcp: lookup maps.googleapis.com on 127.0.1.1:53: read udp 127.0.0.1:41955->127.0.1.1:3: i/o timeout  section=system

**Comment by domesticmouse** [comment]
I'm guessing you just ran the tests? 

The test system is assuming it can run a local server to fake the API end points and just run through the test suite with a set of canned responses. It looks like 127.0.0.1 (localhost) is being mapped to 127.0.1.1 for some reason. 

I think you need a system administrator type person to debug your system configuration.

**Comment by felangga** [comment]
So how to switch from test to run mode ?

**Comment by domesticmouse** [comment]
Tests are only run with `go test`. If you use and of the examples under https://github.com/googlemaps/google-maps-services-go/tree/master/examples you will see responses from our API servers, not the canned data responses.
