### ISSUE TITLE
Errors ignored in DecodePolyline

### ISSUE THREAD

**Issue by rosshemsley** [googlemaps/google-maps-services-go#142]
Looks like errors are printed to stderr instead of returned in the polyline decoder:

https://github.com/googlemaps/google-maps-services-go/blob/master/polyline.go#L49

This means it's not possible to tell if the whole polyline was successfully decoded.

A nicer API would be to propagate the errors up (and leave logging to stderr to the caller)

_edit:_ actually this is `log.Fatal`, so if you try and parse an invalid polyline it will call `os.Exit(1)` - which seems non-ideal..

**Comment by domesticmouse** [comment]
Merged a fix that exposes failing polyline decodes as an `error`.
