### ISSUE TITLE
Shorten comment line length

### ISSUE THREAD

**Issue by bamnet** [googlemaps/google-maps-services-go#143]
I'm trying to build a `DistanceMatrixRequest` and noticed the comments which describe the fields in the struct are pretty long.  They're too long to fit into the default godoc boxes [1] or the larger github code viewer [2].  As a result, to read things like the available `TransitMode` options you need to horizontally scroll.

Reducing the length of the comments and wrapping them earlier would improve ease of use.  WDYT?

[1] https://godoc.org/googlemaps.github.io/maps#DistanceMatrixRequest
[2] https://github.com/googlemaps/google-maps-services-go/blob/master/distancematrix.go#L112

**Comment by domesticmouse** [comment]
Yeah, that presentation is less than stellar. I'm happy to take PRs if you want to have a go at fixing this, or I can have a look at it post I/O. Thanks!
