### ISSUE TITLE
cannot get duration_in_traffic

### ISSUE THREAD

**Issue by dhageuk** [googlemaps/google-maps-services-go#150]
```
	r := &maps.DistanceMatrixRequest{
		Origins:       strings.Split(origins, "|"),
		Destinations:  strings.Split(destinations, "|"),
		Language:      "en",
		DepartureTime: "now",
		Mode:          maps.TravelModeDriving,
		Units:         maps.UnitsMetric,
	}

	resp, err := client.DistanceMatrix(context.Background(), r)
	if err != nil {
		return c.JSON(http.StatusBadRequest, err)
	}

	return c.JSON(http.StatusOK, resp)
```

**Comment by domesticmouse** [comment]
I'm looking at the [documentation](https://developers.google.com/maps/documentation/distance-matrix/intro#DistanceMatrixResponses) for Distance Matrix responses, and I'm not seeing a duration in traffic field per se. Can you be more explicit about what you are expecting? An example request to our API servers would be quite helpful.
