### ISSUE TITLE
accept4: too many open files; retrying in 1s

### ISSUE THREAD

**Issue by speedwheel** [googlemaps/google-maps-services-go#152]
I am using google places api to inside a loop and after 100k loops I always get this error:
[HTTP Server] http: Accept error: accept tcp <myip>:443: accept4: too many open files; retrying in 1s

I am using 2 apis inside the loop: PlaceAutocomplete and PlaceDetails, any thoughts?

**Comment by domesticmouse** [comment]
I’m curious to see your code. The rate limiter should prevent you from opening connections quickly enough to utilise all of your open file quota.
