### ISSUE TITLE
textsearch mismatch between Places API and Go maps package

### ISSUE THREAD

**Issue by Savolro** [googlemaps/google-maps-services-go#153]
Today I've tried using TextSearch from this package and failed.

This is what guide states about _query_ parameter
> This parameter becomes optional if the type parameter is also used in the search request.

(_see [https://developers.google.com/places/web-service/search?authuser=1#TextSearchRequests](url)_)
Calling API with _type_ parameter without query defined works as well.

But this exception is missing in Go code and this function always returns an error if I want to use _type_ instead of _query_.  (_see googlemaps.github.io\maps\places.go:181_)
```go
func (c *Client) TextSearch(ctx context.Context, r *TextSearchRequest) (PlacesSearchResponse, error) {

	if r.Query == "" && r.PageToken == "" {
		return PlacesSearchResponse{}, errors.New("maps: Query and PageToken both missing")
	}
       ...
```

Is this a defect?

**Comment by domesticmouse** [comment]
Yup, that’s now incorrect. You can either submit a PR to fix this, or I’ll look at it when I have time. Thanks!

**Comment by domesticmouse** [comment]
I believe this was fixed in https://github.com/googlemaps/google-maps-services-go/pull/154 yeah? =)
