### ISSUE TITLE
How to use WithClientIDAndSignature()

### ISSUE THREAD

**Issue by TheWrongAlice** [googlemaps/google-maps-services-go#162]
Hi there!

I'm wondering how to generate the signature to pass to this function. According to the Geodata API docs, it should be an encoded version of the url I'm calling, but since I'm using `google-maps-services-go` I don't deal directly with urls.

Alice

**Comment by domesticmouse** [comment]
The [WithClientIDAndSignature](https://godoc.org/googlemaps.github.io/maps#WithClientIDAndSignature) method is intended to support our older Premium customers using [this authorisation](https://developers.google.com/maps/premium/overview#digital-signatures) technique. 

I'm guessing this isn't what you are after, can you give me more detail on which API you are attempting to call?

**Comment by TheWrongAlice** [comment]
Hi @domesticmouse , thank you for your answer.
I am attempting to call the Geocoding API.

In my infrastructure, I already have some credentials that are being used for other integrations, such as Google Cloud Storage. I am hoping that I can use those same credentials for Geocoding as well.
My credentials object looks like this:
```
// GoogleConfig is the parsed google json credentials file
type GoogleConfig struct {
	Type                    string `json:"type"`
	ProjectID               string `json:"project_id"`
	PrivateKeyID            string `json:"private_key_id"`
	PrivateKey              string `json:"private_key"`
	ClientEmail             string `json:"client_email"`
	ClientID                string `json:"client_id"`
	AuthURI                 string `json:"auth_uri"`
	TokenURI                string `json:"token_uri"`
	AuthProviderX509CertURL string `json:"auth_provider_x509_cert_url"`
	ClientX509CertURL       string `json:"client_x509_cert_url"`
}
```

**Comment by TheWrongAlice** [comment]
@domesticmouse got any tips here? :)

**Comment by broady** [comment]
Those look like service account credentials, which I don't think are supported for the Maps APIs.

**Comment by TheWrongAlice** [comment]
Alright. I guess I will just use the api key then. Thank you :)
