### ISSUE TITLE
Problem when trying to use this library via the new Go modules

### ISSUE THREAD

**Issue by philiplb** [googlemaps/google-maps-services-go#163]
Hi,
I have a Go 1.11 project here outside the Go path using the new Go modules.
I executed `go get googlemaps.github.io/maps` and tried to run an example importing "googlemaps.github.io/maps". But if I want to compile it now, I get this error:

> ../../golang/pkg/mod/googlemaps.github.io/maps@v0.0.0-20180903024753-bc340667705e/client.go:30:2: unknown import path "googlemaps.github.io/maps/internal": ambiguous import: found googlemaps.github.io/maps/internal in multiple modules:
> 	googlemaps.github.io/maps v0.0.0-20180903024753-bc340667705e (/Users/philiplb/golang/pkg/mod/googlemaps.github.io/maps@v0.0.0-20180903024753-bc340667705e/internal)
> 	googlemaps.github.io/maps/internal v0.0.0-20180903024753-bc340667705e (/Users/philiplb/golang/pkg/mod/googlemaps.github.io/maps/internal@v0.0.0-20180903024753-bc340667705e)

Is there anything I'm doing wrong here or how could I make this work?

**Comment by domesticmouse** [comment]
Hey @samthor, any ideas on how to fix this issue?

**Comment by Aulet** [comment]
Location not properly in uber driver

**Comment by jpoehnelt** [comment]
I was unable to recreate with any issues here: https://github.com/jpoehnelt/gomaps_mod_test Please reopen if you can reproduce.
