### ISSUE TITLE
containsLocation function

### ISSUE THREAD

**Issue by ofonimefrancis** [googlemaps/google-maps-services-go#164]
I have been playing with the library for a while and wanted to check if a given latitude and longitude falls outside a polygon. 

This is what the **containsLocation** function already does using the google map javascript api, wanted to know if there is any method in this package that can help with that.

**Comment by domesticmouse** [comment]
Hi @ofonimefrancis,

The intent of this API is to be a thin wrapper around the APIs we expose. Core GIS functionality like whether a point is inside a polygon is outside the scope of this project. Thanks!
