### ISSUE TITLE
Remove Deprecated Place Types

### ISSUE THREAD

**Issue by buckhx** [googlemaps/google-maps-services-go#165]
According to the web service docs, the following place types are deprecated:

```
    establishment
    finance
    food
    general_contractor
    grocery_or_supermarket
    health
    place_of_worship
```

https://developers.google.com/places/web-service/supported_types

**Comment by domesticmouse** [comment]
I'd prefer not to break people's code just yet, but happy to delete these in say three months. Thoughts?

**Comment by bgguna** [comment]
I will create a merge-request to remove the deprecated types mentioned in the issue, assuming more than 3 months have passed since the last activity here.
