### ISSUE TITLE
problem: Self import is not allowed

### ISSUE THREAD

**Issue by Eitol** [googlemaps/google-maps-services-go#167]
trying to make other modifications to the code I found this error.
"solve: Self import is not allowed"

Clearly, it is an error when importing.
Ref img:
![image](https://user-images.githubusercontent.com/1043061/45924077-cd31d100-becc-11e8-8c08-80532128dfd6.png)

**Comment by domesticmouse** [comment]
I'm guessing your screenshot is from `encoding.go`. That file is passing `go vet` for me, so I'm guessing your environment is mis-configured.
