### ISSUE TITLE
[question]: Making signing logic exported

### ISSUE THREAD

**Issue by superstas** [googlemaps/google-maps-services-go#172]
Hi there!

I want to ask about "internal" package with [signing logic](https://github.com/googlemaps/google-maps-services-go/blob/master/internal/signer.go).

As premium users, we need to sign our requests to StaticMap API ourselves (https://developers.google.com/maps/documentation/maps-static/get-api-key#premium-auth), but at the same time, we don't want to store "secret key" in mobile apps due to security reason. 

It would be great to have an ability to use `SignURL` func from outside, cause we have to copy/paste or implement the same somewhere aside.

Is it possible to move signing logic to the root or make internal package exported (and name it "signer" for example)?

Thank you!

**Comment by domesticmouse** [comment]
I'd kinda prefer not to expose the signing logic. Is it possible to feed your requests through the [static map API](https://github.com/googlemaps/google-maps-services-go/blob/master/staticmap.go)?

**Comment by superstas** [comment]
I understand, but for some reasons, it doesn't fit for us.
It would work if `StaticMapRequest` had method `SignURL(clientID string, secret []byte)`

for instance:
```go
// create request
r := StaticMapRequest{}
s := r.SignURL(clientID, secret) // staticMapAPI.path is used inside
```
Unfortunately, AFAIU in that case, it should be added to each request for consistency, and this is not a good way.

Anyway, thanks for helping!

**Comment by domesticmouse** [comment]
Can you explain how the addition of this method to the StaticMapRequest would help?

**Comment by superstas** [comment]
Sure. I have a mobile client that has already had an implemented logic showing pictures generated via StaticMap API. It used to work with API_KEY until the rules have changed.

Now it sends to the backend a StaticMap API query for signing. As for instance, a query `client=clientID&origin=Toronto` gets a signed URL `https://maps.googleapis.com/maps/api/staticmap?client=clientID&origin=Toronto&signature=mPvi3crsSSM1olW2lXmzUWcLB_8=` as a response. 

I agree that my previous proposal is not correct. Having a method `Sign` is useless, cause it adds extra step of converting `client=clientID&origin=Toronto` -> `StaticMapRequest`. 

In case, of making `Sign` func public, private `apiConfig` should be exported as well.  

So, I think the current implementation is good enough.

**Comment by domesticmouse** [comment]
Cool, thanks for the clarification. I'm glad the current design is workable for you.
