### ISSUE TITLE
[staticmaps]: It seems the implementation of styled maps is broken

### ISSUE THREAD

**Issue by superstas** [googlemaps/google-maps-services-go#174]
HI there!

I've faced with some problems during using of styled maps.
Let's say I want to send a query that would contain following fields:

- `feature:all|element:geometry|color:0xeeaabb|visibility:simplified`
- `feature:all|element:labels.icon|saturation:-50|weight:2`
- `feature:water|element:geometry.fill|color:0xff0000`
- `feature:landscape.natural|element:geometry|color:0x0000ff|width:50`

I'm creating following request:
```go
r := StaticMapRequest{
		Size: "600x600",
		Markers: []Marker{
			Marker{
				Location: []LatLng{
					LatLng{
						Lat: 51.477222,
						Lng: 0,
					},
				},
			},
		},
		MapStyles: MapStyle{
			"all": Elements{
				"geometry": StyleRules{
					"color":      "0xeeaabb",
					"visibility": "simplified",
				},
				"labels.icon": StyleRules{
					"saturation": "-50",
					"weight":     "2",
				},
			},
			"water": Elements{
				"geometry.fill": StyleRules{
					"color": "0xFF0000",
				},
			},
			"landscape.natural": Elements{
				"geometry": StyleRules{
					"color": "0x0000FF",
					"width": "50",
				},
			},
		},
	}
```

It generates the following URL:
```
key=<YOUR API KEY HERE>&markers=51.477222,0&size=600x600&style=feature:all||labels.icon|weight:2|weight:2|geometry|visibility:simplified|visibility:simplified&style=feature:water||geometry.fill|color:0xFF0000&style=feature:landscape.natural||geometry|width:50|width:50
```
There are a few problems here:
- I got strange duplicates. ( e.g. `weight:2|weight:2` )
- `style` has double vertical bar between `feature` and `geometry`

One extra problem:
AFAIU, the part that contains feature `all` is invalid at all ( please correct me if i'm wrong ): I expect that the result url would look like: `...style=feature:all|element:geometry|color:0xeeaabb|visibility:simplified&style=feature:all|element:labels.icon|saturation:-50|weight:2...` ( according to the doc I can't merge elements with different rules inside the same feature like `style=feature:all|element:geometry|color:0xeeaabb|visibility:simplified|element:labels.icon|saturation:-50|weight:2` )

That leads me to the question: is it correct to have a map `map[FeatureName]Elements` where FeatureName might repeat, and the resulting URL has to contain a single `style` argument for each requested `FeatureName`?

I would fix it, but we have to discuss the most appropriate way of fixing.
Thanks!

**Comment by domesticmouse** [comment]
Honestly, I'm not an expert in the static map API, so I'm happy to take guidance on paths forward here.

I'd start with a PR that collects test cases for problematic requests. Then we can figure out how to fix them.

**Comment by regeda** [comment]
https://github.com/googlemaps/google-maps-services-go/pull/176

**Comment by domesticmouse** [comment]
Can we call this fixed now?

**Comment by superstas** [comment]
@domesticmouse yes, I think so!
Thx!
