### ISSUE TITLE
How to get more results from NearbySearch?

### ISSUE THREAD

**Issue by weihesdlegend** [googlemaps/google-maps-services-go#185]
By default, the api only returns around 20 results. I tried to use the page token obtained from previous search to get the results on next page. But the following code does not work, saying that the request is invalid. Sorry have to ask it here, did some research on Google but could not figure out.

for i:=0; i < 3; i++{
		req := &maps.NearbySearchRequest{
			Location: &latlng,
			Radius:   1000,
			Type: "restaurant",
			PageToken:token,
		}

		res, err := client.NearbySearch(context.Background(), req)
		if err != nil{
			log.Fatal(err)
		}

		fmt.Printf("Got %d results on this page \n", len(res.Results))
		fmt.Printf("Next page token is %s \n", res.NextPageToken)

		token = res.NextPageToken
}

**Comment by domesticmouse** [comment]
Per the [Places API documentation](https://developers.google.com/places/web-service/search#PlaceSearchPaging):

By default, each Nearby Search or Text Search returns up to 20 establishment results per query; however, each search can return as many as 60 results, split across three pages. If your search will return more than 20, then the search response will include an additional value — `next_page_token`. Pass the value of the `next_page_token` to the `pagetoken` parameter of a new search to see the next set of results. If the `next_page_token` is null, or is not returned, then there are no further results. *There is a short delay between when a next_page_token is issued, and when it will become valid.* Requesting the next page before it is available will return an `INVALID_REQUEST` response. Retrying the request with the same `next_page_token` will return the next page of results.

**Comment by weihesdlegend** [comment]
Thanks @domesticmouse ! I tried couple of delay for getting valid response. And if I make the program sleep for 1 second, we cannot get valid results using NextPageToken. If we make the program sleep for 1.5 seconds, we get intermittent interruption. If we sleep for 2 seconds, we can almost always get valid results. Is there a lower bound on the time the token becomes valid?

**Comment by domesticmouse** [comment]
I don't know what the required delay is, and I don't believe we have documented it. So I'd err on the side of caution.

**Comment by realchrisolin** [comment]
Can I / we get an official answer as this question applies to the "new" Places API. Specifically, the document at https://developers.google.com/maps/documentation/places/web-service/nearby-search indicates this is not possible and trying to specify a maxResultCount greater than 20 throws an error, and there's no documented support for some sort of equivalent of `next_page_token`.

```
{
  "error": {
    "code": 400,
    "message": "Max number of place results to return must be between 1 and 20 inclusively.",
    "status": "INVALID_ARGUMENT"
  }
}
```

Not being able to obtain more than 20 results makes this endpoint fairly useless.

**Comment by wangela** [comment]
@realchrisolin For the Places API (New), see #291 which provides a link to the Go client libraries for new APIs including Places API (New). To request pagination beyond 20 results in Nearby Search, "star" [this feature request in the Places API issue tracker](https://issuetracker.google.com/issues/314796720) to upvote it and receive notifications when the issue is updated.
