### ISSUE TITLE
Support for Street View API [New Feature]

### ISSUE THREAD

**Issue by J7mbo** [googlemaps/google-maps-services-go#187]
I'm opening this issue as a starting point for hopefully including Street View api capabilities.

Are you accepting PRs? Can I help out? Or does something already exist? @domesticmouse Can you weight on this

**Comment by amuramoto** [comment]
This library is intended to support our web services API, so StreetView isn't included because it's intended for front end use. We'd be happy to talk about a PR though. What did you have in mind for why SV should be included here?

**Comment by J7mbo** [comment]
Thanks for your reply. My initial thoughts:

- Whilst the StreetView image is intended to be displayed in the browser there is merit in utilising a back-end service to retrieve this data, especially given credentials as a requirement.
- It would be relatively simple to add support for it given the current clean code in this codebase.
- It would be great to have a google-supported Go library for Streetview.
- My initial expectation as a consumer would be that `googlemaps/` would contain StreetView functionality somewhere. This is of course subjective.

A downside that I can think of:

- I only need this on the Go-side. You'd either have to have diverging functionality between other language's repositories in `googlemaps/` (I haven't checked whether or not this is already the case) and could wait for PRs in there, or if the same functionality is required then it'd be extra work.

**Comment by domesticmouse** [comment]
Which Google Maps Web Service API are you intending on retrieving the Street View photospheres from?

**Comment by J7mbo** [comment]
The Street View static API.

**Comment by domesticmouse** [comment]
I'm happy to accept PRs for this new service, as long as it in the same spirit as the rest of the APIs, and it has similar code coverage to the rest of the API surface. Thanks!
