### ISSUE TITLE
Support quotaUser parameter for each request

### ISSUE THREAD

**Issue by xxlionheartxxx** [googlemaps/google-maps-services-go#190]
Hi, 

Could you add one QuotaUser parameter for each request struct?

Reference:
https://cloud.google.com/apis/docs/capping-api-usage?visit_id=636928288720788663-2735565271&rd=1

thanks a lot,

**Comment by domesticmouse** [comment]
We accept PRs =)

**Comment by xxlionheartxxx** [comment]
I tried to add QuotaUser parameter but it not working, then i found a solution for my project that build a middleware rate limiter.
https://redis.io/commands/INCR

**Comment by amuramoto** [comment]
Closing since an alternative solution was found
