### ISSUE TITLE
go get googlemaps.github.io/maps fails on Go tip

### ISSUE THREAD

**Issue by rogpeppe** [googlemaps/google-maps-services-go#192]
Since [this issue](https://github.com/golang/go/issues/29618) was fixed, it seems that it's not possible to do `go get googlemaps.github.io/maps` without getting an error unless you use the `--insecure` flag. See [this Go issue](https://github.com/golang/go/issues/32071).

**Comment by domesticmouse** [comment]
I'm unsure how to fix this. Both http://googlemaps.github.io/maps and https://googlemaps.github.io/maps redirect.

**Comment by bcmills** [comment]
This appears to be a bug in GitHub Pages (see https://github.com/isaacs/github/issues/289#issuecomment-430941254).

Ideally, you should escalate this to GitHub so that they can prioritize a fix.

**Comment by jpoehnelt** [comment]
I'm unable to recreate this issue and it appears a fix was deployed in late May https://github.com/golang/go/issues/32071#issuecomment-496574794.
