### ISSUE TITLE
Top-level Status Codes for Distance Matrix

### ISSUE THREAD

**Issue by sabir012** [googlemaps/google-maps-services-go#193]
Hi Team, 
As mentioned in developer guide for google maps api, distance matrix can also provide top level status codes (like OK, INVALID_REQUEST, MAX_ELEMENTS_EXCEEDED and etc). However, distance matrix just returns error and response model where does not exists status code. Is there anyway to get a status for each distance matrix call?

**Comment by domesticmouse** [comment]
I'm happy to review suggested API changes in the form of PRs

**Comment by jpoehnelt** [comment]
Dropped this to lowest priority since it will likely be a breaking change across all APIs. Perhaps we could do something along the lines of:

```
func (c *Client) DistanceMatrix(ctx context.Context, r *DistanceMatrixRequest) (*DistanceMatrixResponse, StatusCode, error) {
```
