### ISSUE TITLE
Keep PlaceAutocompleteRequest unmodified when making a request

### ISSUE THREAD

**Issue by kirylandruski** [googlemaps/google-maps-services-go#208]
func (r *PlaceAutocompleteRequest) params() modifies Components values,
which may cause a bug if the same request value is used to make multiple requests (for example to do retries).
I fixed that in our fork https://github.com/gojuno/google-maps-services-go/pull/2/commits/185a1358164d7473ea5ac5d39f8df653ee4bfdcd this way.
Thanks!

**Comment by jpoehnelt** [comment]
@kirylandruski mind submitting a pr? Thanks!

**Comment by jpoehnelt** [comment]
@kirylandruski can you sign the cla in the below pr to merge the commit from your fork? https://github.com/googlemaps/google-maps-services-go/pull/216

**Comment by jpoehnelt** [comment]
@kirylandruski can you sign the cla? see above links. thanks!

**Comment by jpoehnelt** [comment]
closed in #236
