### ISSUE TITLE
 go get googlemaps.github.io/maps stops working

### ISSUE THREAD

**Issue by zhixinwen** [googlemaps/google-maps-services-go#227]
package googlemaps.github.io/maps: unrecognized import path "googlemaps.github.io/maps" (parse https://googlemaps.github.io/maps?go-get=1: no go-import meta tags ())

So as dep, looks like the website page is gone.

**Comment by eparziale** [comment]
Same issue here. Our dep builds are failing with 

✗ unable to deduce repository and source type for "googlemaps.github.io/maps": unable to read metadata: go-import metadata not found

**Comment by jpoehnelt** [comment]
Will take a look. Looks like the Github pages redirect is not there any longer. @arriolac

**Comment by jpoehnelt** [comment]
Looks like we had an integration removed by @google-admin.

**Comment by djvt** [comment]
same issue for us. dep builds failing

**Comment by arriolac** [comment]
That page should be back up. Please let us know if this is still an issue.

**Comment by f-ewald** [comment]
Everything works. Thanks.
