### ISSUE TITLE
Support for API Quota along with RPS

### ISSUE THREAD

**Issue by KumarAshish155** [googlemaps/google-maps-services-go#228]
**Is your feature request related to a problem? Please describe.**
We have a quota limit of 5000 requests per 100 seconds. Instead of limiting to 50 RPS, we need to optimize our speed to fetch 5000 records as soon as possible and can wait 100 seconds for the next requests. 

 **Describe the solution you'd like**
We can have additional configuration for quota which takes in the number of requests and the period.

**Comment by jpoehnelt** [comment]
Thanks for the request. At this time I'm hesitant to add any additional logic to the ratelimiting and more inclined to remove it. I think there are just too many scenarios to support.

**Comment by AlphaWong** [comment]
hi.

I think you can set the number of `requestsPerSecond` to `0`. After u set it to `0`, I think you can have you customized hook about the rate limited. 
```go
func NewClient(options ...ClientOption) (*Client, error) {
...
	if c.requestsPerSecond > 0 {
		c.rateLimiter = rate.NewLimiter(rate.Limit(c.requestsPerSecond), c.requestsPerSecond)
	}
...
}

func (c *Client) awaitRateLimiter(ctx context.Context) error {
	if c.rateLimiter == nil {
		return nil
	}
	return c.rateLimiter.Wait(ctx)
}
```
