### ISSUE TITLE
Type of supermarket is missing

### ISSUE THREAD

**Issue by voscob** [googlemaps/google-maps-services-go#242]
https://github.com/googlemaps/google-maps-services-go/blob/28505704dfe67587df859a417b16c0dcbc2dc411/types.go#L272

You should add the following lines with supermarket's type:

Line after 272:
    PlaceTypeSupermarket = PlaceType("supermarket")
Line after 448:
    case "supermarket":
        return PlaceTypeSupermarket, nil

**Comment by jpoehnelt** [comment]
closed via #243
