### ISSUE TITLE
Places: nearby search results do not contain opening hours info

### ISSUE THREAD

**Issue by timwangmusic** [googlemaps/google-maps-services-go#249]
#### Environment details

1. Nearby search API
2. MacOS Catalina 10.15.7
3. SDK: googlemaps.github.io/maps v1.2.3

#### Steps to reproduce

1. Make a basic nearby search request with fields specified in the code example below.
2. Check `maps.PlacesSearchResponse.Results.OpeningHours`
3. For some places the OpeningHours pointer is `nil`, and for others the `WeekdayText` and `Periods` slice lengths are zero

#### Code example

```go
        // basic request
	mapsReq := maps.NearbySearchRequest{
		Type:      maps.PlaceType(placeType),
		Location:  &latLng,
		Radius:    radius,
		PageToken: pageToken,
		RankBy:    maps.RankBy(rankBy),

```

Comment: are we supposed to always use DetailedSearch to get the `OpeningHours` info?

**Comment by weihesdlegend** [comment]
Hi, can some one take a look at the issue?

**Comment by AlphaWong** [comment]
> Hi, can some one take a look at the issue?

Can u offer a curl request for it. 
Then I can try it on my side.

**Comment by weihesdlegend** [comment]
Sorry for late response. I tried this call `https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-33.8670522,151.1957362&rankby=prominence&type=restaurant&radius=5000&key=YOUR_API_KEY`. I still can see that the opening_hours field only contains a Boolean value { open_now: true }

Maybe this is intended? The original issue was not about the REST API, but the maps Golang client. From the type OpeningHours struct it is not obvious at all that users should expect Periods []OpeningHoursPeriod to be nil.

**Comment by timwangmusic** [comment]
Thanks @wangela for the investigation. So I think for API users the procedure to get details around a location is first do nearby search and use place details API to get place details with place ID?

**Comment by wangela** [comment]
@timwangmusic sorry for missing your question. Yes, get the Place ID from the search results and use that Place ID to request Place Details.
