### ISSUE TITLE
Is there a way to set range for radius parameters?

### ISSUE THREAD

**Issue by FatimaMaj** [googlemaps/google-maps-services-go#259]
As I know the Nearby Search or Text Search returns up to 20 results.  And if we use 'next_page_token', each search can return as many as 60 results.
My question is that if for example my request has in total 100 results, and I want to take the results that are in the last page token, how can I take this result? 
In other words I don't want the first 60 results. I want for example the last 30 result.

**Comment by wangela** [comment]
The short answer is no you cannot define a donut-style shape as your location bias, but the `radius` and `rankby` parameters can work together in getting to the results you want. If your goal is to get prominent places farther away from your search origin, set the radius larger and leave the `rankby` parameter as its default value `prominence`. Documentation of the underlying API behind this client is here for [Nearby Search](https://developers.google.com/maps/documentation/places/web-service/search-nearby#radius) and [Text Search](https://developers.google.com/maps/documentation/places/web-service/search-text#radius).

**Comment by FatimaMaj** [comment]
Thanks for replying.
