### ISSUE TITLE
googleMap Error: connect ECONNREFUSED 0.0.0.0:443

### ISSUE THREAD

**Issue by 891806797** [googlemaps/google-maps-services-go#262]
I can return normally when I call in the browser, but I will report an error when I call in golang or Java or postman: Dial TCP 0.0.0:443: Connect: connection rejected. What's the problem? thank you very much indeed

**Comment by jpoehnelt** [comment]
Seems like a firewall or similar issue if it is happening across languages and client libraries. Closing as there is not enough information and it is unrelated to this library.
