### ISSUE TITLE
Static maps map_id parameter support

### ISSUE THREAD

**Issue by rockaport** [googlemaps/google-maps-services-go#269]
It looks like the map_id parameter isn't supported. I didn't see any reference to it in the static maps source code. It looks like an easy change to add it in there. Let me know if it's supported and I'm missing something or you'd like for me to submit a PR.

Thanks

 **Is your feature request related to a problem? Please describe.**
It looks as if the [map_id](https://developers.google.com/maps/documentation/maps-static/start#URL_Parameters) parameter is not supported.

 **Describe the solution you'd like**
map_id parameter is supported. Added to the `StaticMapRequest` struct.

 **Describe alternatives you've considered**
Forking and making this modification myself. Which I'm not opposed to and creating a pull request.

**Comment by wangela** [comment]
We welcome your PR! Thank you for contributing. Be sure to accept the CLA described in the [contributing guide](https://github.com/googlemaps/google-maps-services-go/blob/master/CONTRIB.md).
