### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by rugo** [googlemaps/google-maps-services-go#54]
Hey guys,

I'm getting this when installing the package:

    $ go get googlemaps.github.io/maps
    # googlemaps.github.io/maps
    ../../go/src/googlemaps.github.io/maps/client.go:71: syntax error: unexpected range, expecting {
    ../../go/src/googlemaps.github.io/maps/client.go:76: non-declaration statement outside function body
    ../../go/src/googlemaps.github.io/maps/client.go:77: syntax error: unexpected }

My system:

    $ go version
    go version go1.3.3 linux/amd64
    $ uname -a
    Linux rg-tp 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u6 (2015-11-09) x86_64 GNU/Linux

Got any ideas what happened there? 
Does

     for range time.Tick(time.Second / time.Duration(c.requestsPerSecond)) {

from client.go:71 use a language feature not yet available in 1.3.3?
The code

    for _ = range time.Tick(time.Second / time.Duration(c.requestsPerSecond)) {

works for me. The docs say Go version 1.x or newer is fine.

**Comment by domesticmouse** [comment]
I've just confirmed with Travis that 1.3 is indeed tripping up on that construct. You can either upgrade Go on your machine, or submit a patch that fixes the issue =)
