### ISSUE TITLE
client.go prefill causing batch of queries to hit 'over qps'  limit

### ISSUE THREAD

**Issue by kentvv** [googlemaps/google-maps-services-go#64]
Hi there.

I am using this library for direction requests.

Over a given day i have noticed in my google for work logs i am hitting the query limit.

With the query per seconds set at 10 in the library. I get a inconsistent amount of requests coming through with the OVER_QPS_LIMIT over the day. I believe this limit is enforced in part due to system load on google servers?

I believe this is caused by the following [prefill line](https://github.com/googlemaps/google-maps-services-go/blob/master/client.go#L66) in client.go? 

I have attached a sample [wireshark log](http://pastebin.com/PCnCk4kn) which shows that the prefill is making 10 request occur instantly, followed by the correct rate after that (a request every 200 milliseconds).

Thoughts?

**Comment by domesticmouse** [comment]
Thanks for digging into this, both the wireshark log and finding the right point for a fix in client.go.
