### ISSUE TITLE
Add fare to directions response

### ISSUE THREAD

**Issue by croachrose** [googlemaps/google-maps-services-go#72]
Based on the documentation at https://developers.google.com/maps/documentation/directions/intro#DirectionsResponseElements there is a fare option returned in the directions request for transit if all legs contain fare information.

**Comment by domesticmouse** [comment]
Please feel free to create a Pull Request to implement this change =)

**Comment by domesticmouse** [comment]
I've just committed some code that should handle Fare information. If you can supply a query that returns Fare information I'll add a matching test. Thanks!

**Comment by croachrose** [comment]
Origin: 35.7777111, -78.625354
Destination: 35.7826242, -78.6547025
Mode: 'transit'

That should give you back transit directions with a fare.

**Comment by domesticmouse** [comment]
Thanks, tests are in. Please note, I changed the API for fares while testing.
