### ISSUE TITLE
AppEngine support

### ISSUE THREAD

**Issue by ghosttie** [googlemaps/google-maps-services-go#73]
When I try to use the maps API in Google AppEngine I get this error:

> 2016/06/25 10:09:23 ERROR: Get https://maps.googleapis.com/maps/api/geocode/json?address=30080&key=yaddayadda: http.DefaultTransport and http.DefaultClient are not available in App Engine. See https://cloud.google.com/appengine/docs/go/urlfetch/

Is there any chance of urlfetch support being added?

**Comment by domesticmouse** [comment]
This library should work as is on AppEngine, but I believe you need to import `google.golang.org/appengine` and thread through the `appengine.NewContext(r *http.Request)` as the context to requests. If you have a small repro case that you can put up on github I'll have a go at making the modifications required to get it working.

**Comment by dlutton** [comment]
I was able to make a successful request using this library in Google AppEngine using the below:
```
ctx := appengine.NewContext(r)
client := urlfetch.Client(ctx)

c, err := maps.NewClient(maps.WithAPIKey("yourKey"), maps.WithHTTPClient(client))
```

**Comment by domesticmouse** [comment]
As this works, I'm closing this issue out.
