### ISSUE TITLE
distancematrix 'avoid' multiple is deprecated

### ISSUE THREAD

**Issue by Loster83** [googlemaps/google-maps-services-go#78]
According to the documentation for distancematrix in 'avoid' parameter you can use only one restriction.
But your implementation supports multiple:
https://github.com/googlemaps/google-maps-services-go/blob/master/distancematrix.go#L88

If you look at java client - it allows only single restriction:
https://github.com/googlemaps/google-maps-services-java/blob/master/src/main/java/com/google/maps/DistanceMatrixApiRequest.java#L122

**Comment by domesticmouse** [comment]
So my handling of Avoid parameter for DIstanceMatrix was completely broken. I believe it should now work as advertised. Thanks!
