### ISSUE TITLE
Google Distance Matrix API is returning walking distance even though Mode:transit and TransitMode:train,subway are specified

### ISSUE THREAD

**Issue by shawnps** [googlemaps/google-maps-services-go#79]
Sample coordinates are Shibuya Station to Shinjuku Station, should be roughly 9 min travel time by train:

```
    c, err := maps.NewClient(maps.WithAPIKey("api-key"))
    if err != nil {
        log.Fatal(err)
    }   

    r := maps.DistanceMatrixRequest{
        Origins:      []string{"35.658336, 139.701774"},
        Destinations: []string{"35.690823, 139.699579"},
        Mode:        maps.TravelModeTransit,
        TransitMode: []maps.TransitMode{maps.TransitModeTrain, maps.TransitModeSubway},
    }   
    fmt.Printf("%#v\n", r)
    dmr, err := c.DistanceMatrix(context.Background(), &r) 
    if err != nil {
        log.Fatal(err)
    }   
    for _, row := range dmr.Rows {
        for _, elem := range row.Elements {
            fmt.Println(elem.Status, elem.Duration, elem.Distance.HumanReadable)
        }   
    }  
```

```
➜  ~  go run foo.go 
maps.DistanceMatrixRequest{Origins:[]string{"35.658336, 139.701774"}, Destinations:[]string{"35.690823, 139.699579"}, Mode:"transit", Language:"", Avoid:"", Units:"", DepartureTime:"", ArrivalTime:"", TrafficModel:"", TransitMode:[]maps.TransitMode{"train", "subway"}, TransitRoutingPreference:""}
OK 51m25s 4.3 km
```

Is there something I'm missing?

**Comment by shawnps** [comment]
It gets shorter when I exclude Mode and TransitMode, but it's still quite long (returns 17m, vs. the ~9m it should actually be)

**Comment by domesticmouse** [comment]
Is the client library generating the wrong API calls, or is the data returned by the API incorrect? If it is the API that is returning incorrect data, please raise an issue at https://code.google.com/p/gmaps-api-issues/issues/entry?template=Distance%20Matrix%20API%20-%20Bug

Thanks!

**Comment by shawnps** [comment]
@domesticmouse the client library appears to have the correct things set on the struct, but I didn't dig in on whether the request or response was incorrect because I wasn't sure how to find the raw values. I'll take another look tonight.

**Comment by domesticmouse** [comment]
I'm assuming this is actually a data issue with the Google Maps Web Service APIs. Please raise a ticket on https://code.google.com/p/gmaps-api-issues/

Thanks!
