### ISSUE TITLE
Autocomplete type

### ISSUE THREAD

**Issue by Deuteu** [googlemaps/google-maps-services-go#84]
According to [Places API Web Service documentation](https://developers.google.com/places/web-service/autocomplete) type must be in this [list](https://developers.google.com/places/web-service/autocomplete#place_types) (geocode, establishment, address, ...) but apparently in the [call to the API](https://github.com/googlemaps/google-maps-services-go/blob/ce8994f7a138534e9da9fd27c5424eeea20ac563/places.go#L635) which uses [PlaceType](https://github.com/googlemaps/google-maps-services-go/blob/master/types.go#L176) (through [PlaceAutocompleteRequest](https://github.com/googlemaps/google-maps-services-go/blob/ce8994f7a138534e9da9fd27c5424eeea20ac563/places.go#L694)) which is not the same kind of type as mentioned before.

IMHO, you are using [PlaceType of PlaceSearch](https://developers.google.com/places/supported_types) instead of [PlaceType of PlaceAutocomplete](https://developers.google.com/places/web-service/autocomplete#place_types)

So, according to my tests, [your example](https://github.com/googlemaps/google-maps-services-go/blob/ce8994f7a138534e9da9fd27c5424eeea20ac563/examples/places/placeautocomplete/placeautocomplete.go) doesn't work with the [example of the api doc](https://developers.google.com/places/web-service/autocomplete#place_autocomplete_responses)

**Comment by domesticmouse** [comment]
I believe this is now fixed. Please re-open if further work is required. Thanks!
