### ISSUE TITLE
Making Client an interface, so that it could be mocked

### ISSUE THREAD

**Issue by sazary** [googlemaps/google-maps-services-go#92]
Hi   
I'm using this package to use google maps, but I have a problem: I'm using a singleton `Client` object for all my requests, but `Client` isn't an interface, so I don't know how can I mock it for unit testing, as is required by `github.com/golang/mock` or `github.com/vektra/mockery`.  
Do I have to wrap it in another interface and object to be able to mock it?

**Comment by domesticmouse** [comment]
I'm not quite sure what sort of changes you would like us to implement? My understanding is that if you define an interface that exposes the functionality that Client implements that you need to test, we would automatically implement it?

Please feel free to create a pull request with the changes you require to make this work for you so I can get a feeling for what you require. Thanks!

**Comment by domesticmouse** [comment]
Closing this out for now. Please feel free to re-open if you would like to propose a path forward. Thanks!
