### ISSUE TITLE
Support for the Geolocation API [New Feature]

### ISSUE THREAD

**Issue by timfallmk** [googlemaps/google-maps-services-go#97]
The python version of this library appears to support the [Geolocation API](https://developers.google.com/maps/documentation/geolocation/intro). It would be wonderful to add that here.

**Comment by YijinLiu** [comment]
+1

**Comment by adrien3d** [comment]
+1

**Comment by domesticmouse** [comment]
I've just merged @ryankurte's #99, please let me know if we are missing functionality that you all require. Thanks!
